Code_Samurai_Hackathon/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import observer.views as observer_views
import observer.authentication_module as observer_au

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', observer_views.load, ''),
                  path('', include('observer.urls', namespace='observer')),
                  path('login/', observer_au.log_in, name='login'),
                  path('logout/', observer_au.logout_request, name='logout'),
                  path('registration/', observer_au.registration, name='register'),
                  path('utility/', include('utility_engines.urls', namespace='utility')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

observer/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import observer.views as observer_views
import observer.review_proposal as review_view

app_name = 'observer'

urlpatterns = [
    path('api/projects/', observer_views.projects, name='projects'),
    path('api/all-projects/', observer_views.all_projects, name='all-projects'),
    path('api/projects/filter', observer_views.filter_projects, name='filter_projects'),
    path('', observer_views.load, name='home'),
    path('post_feedback/', observer_views.post_feedback, name='post_feedback'),
    path('project-proposal/', observer_views.project_proposal, name='project-proposal'),
    # path('project-proposal/update-proposal/', observer_views.update_proposal, name='update-proposal'),
    path('update-proposal/<int:pk>/', observer_views.proposal_update_form, name='update-proposal-form'),
    path('add-rating/', observer_views.add_rating, name='add-rating'),
    path('review-project-proposal/<int:pk>/', review_view.detail_project_proposal, name='detail-project-proposal'),
    path('approve-proposal/<int:pk>/', review_view.approve_proposal, name='approve-proposal'),
    path('reject-proposal/<int:pk>/', review_view.reject_proposal, name='reject-proposal'),
    path('review-project-proposal/', review_view.review_project_proposal, name='review-project-proposal'),
    path('running-project/', review_view.running_project, name='running-project'),
    path('running-project/<int:pk>/', review_view.detail_running_project, name='detail-running-project'),

    path('export-data/', observer_views.export_data, name='export-data'),
    path('export-data-search/', observer_views.export_data_search, name='export-data-search'),
    path('test/', observer_views.test_func, name='test'),
    path('404/', observer_views.load_not_found, name='404'),
    # path('export-data/export-csv/', observer_views.csv_extractor, name='csv-extractor'),
]

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>BUET NOOBS - Code Samurai</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <!-- <link href="css/styles.css" rel="stylesheet" /> -->
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
</head>

<body class="sb-nav-fixed">
{% include 'components/topbar.html' %}
<div id="layoutSidenav">
    {% include 'components/sidebar.html' %}

    <div id="layoutSidenav_content">


        {% block map %}
        {% endblock %}

        {% block projects %}
        {% endblock %}

        {% block export_data %}
        {% endblock %}

        {% block export_data_proposed %}
        {% endblock %}

        {% block notFound %}
        {% endblock %}

        <div>
            {% include 'components/toast-message-success.html' %}
            {% include 'components/toast-message-failure.html' %}
        </div>


        <footer class="py-4 bg-light mt-auto">
            <div class="container-fluid px-4">
                <div class="d-flex align-items-center justify-content-center small">
                    <div class="text-muted">Copyright &copy; BUET NOOBS</div>

                </div>
            </div>
        </footer>
    </div>

</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<!-- <script src="{% static 'assets/demo/chart-area-demo.js' %}"></script>
<script src="{% static 'assets/demo/chart-bar-demo.js' %}"></script> -->
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest" crossorigin="anonymous"></script>
<script src="{% static 'js/datatables-simple-demo.js' %}"></script>
<script src="{% static 'js/project-issue.js' %}"></script>
<script src="{% static 'js/proposed_project.js' %}"></script>
<script src="{% static 'js/csv-extractor.js' %}"></script>
</body>

</html>

templates/base/export_data.html
{% extends 'base/base.html' %}

{% block export_data %}
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Export Data</h1>
            <div class="col-md-4">
                <form action="{% url 'observer:export-data-search' %}" method="POST">
                    {% csrf_token %}
                    <input type="text" class="form-control my-3 " name="search" placeholder="">
                    <input type="checkbox" name="is_approved"> Approved

                    <button type="submit" class="btn btn-primary">Search</button>
                </form>
            </div>

            <div class=" d-flex justify-content-end">
                <button class="btn btn-outline-primary"> Print </button>
            </div>

            <table class="table table-striped table-hover">
                <thead>
                <th>Project Name</th>
                <th>Start Date</th>
                <th>Time Span(year)</th>
                <th>Expected Completion</th>
                <th>Agency</th>
                </thead>
                {% for project in projects %}
                    <tr>
                        <td>{{ project.project.name }}</td>
                        <td>{{ project.start_date }}</td>
                        <td>{{ project.project.timespan }}</td>
                        <td>{{ project.expected_end }}</td>
                        <td>{{ project.project.executing_agency.name }}</td>
                    </tr>
                {% endfor %}

                <tbody>

                </tbody>
            </table>


        </div>
    </main>
{% endblock %}

templates/base/home.html
{% extends 'base/base.html' %}

{% block map %}
<main>
    <div class="container-fluid px-4">
        <h1 class="mt-4">Office</h1>
        <ol class="breadcrumb mb-4">
            <li class="breadcrumb-item active">Location of the projects</li>
        </ol>
        <input type="hidden" id="location-hidden">
        {% include 'components/modal.html' %}


        {% include 'components/map.html' %} {# {% include 'cards.html' %}#} {# {% include 'charts.html' %}#}
        {# {% include 'datatable.html' %}#}
    </div>
</main>

{% endblock %}

templates/base/projects.html
{% extends 'base/base.html' %}
{% load static %}

{% block projects %}
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Proposed Projects by the Agency</h1>
            <div class="row">
                <div class="col shadow-lg m-4">
                    <div class="row text-center mb-3">
                        <h2>Propose Project</h2>
                    </div>
                    <div class="proposal-form form-control">
                        <form method="post" action="{% url 'observer:project-proposal' %}">
                            {% csrf_token %}
                            <label for="propose-form-name">Project name:</label><br>
                            <input type="text" id="propose-form-name" class="form-control" name="propose-form-name" value="{{ data.name }}"><br>

                            <label for="propose-form-area">Location Area:</label><br>
                            <input class="form-control" type="text" id="propose-form-area form-control"
                                   name="propose-form-area" value="{{data.area}}"><br>
                            <label for="propose-form-lat">Latitude</label><br>
                            <input class="form-control" type="text" id="propose-form-lat" name="propose-form-lat"
                                   required value="{{data.lat}}"><br>
                            <label for="propose-form-long">Longitude</label><br>
                            <input class="form-control" type="text" id="propose-form-long" name="propose-form-long"
                                   required value="{{data.long}}"><br>


                            <label for="propose-form-cost">Project cost:</label><br>
                            <input class="form-control" type="number" id="propose-form-cost"
                                   name="propose-form-cost" value="{{data.cost}}"><br>

                            <label for="propose-form-timespan">Project timespan:</label><br>
                            <input class="form-control" type="number" id="propose-form-timespan"
                                   name="propose-form-timespan" value="{{data.timespan}}"><br>

                            <label for="propose-form-goal">Project goal:</label><br>
                            <input class="form-control" type="textarea" id="propose-form-goal" name="propose-form-goal" value="{{data.goal}}"><br>
                            <div class="row text-center px-2">
                                <button type="submit" class="btn btn-outline-primary">{% if data.name %}Update {% else %} Propose {% endif %}</button>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="col shadow-lg m-4">
                    {% include 'components/location_register_map.html' %}

                    <div class="d-flex justify-content-center">
                        <h4 class="mt-4">
                            Drag the marker to select the project coordinate
                        </h4>
                    </div>
                </div>
            </div>

            <table class="demo-table">
                <tr class="demo-tr">
                    <th class="demo-tdh">Name</th>
                    <th class="demo-tdh">Location</th>
                    <th class="demo-tdh">Cost</th>
                    <th class="demo-tdh">Timespan</th>
                    <th class="demo-tdh">Goal</th>
                    <th class="demo-tdh">Proposed Date</th>
                    <th class="demo-tdh">Edit Proposal</th>
                </tr>
                {% for p in context %}
                    <tr class="demo-tr">
                        <td class="demo-tdh">{{ p.name }}</td>
                        <td class="demo-tdh">
                            {% for l in p.location %}
                                {{ l }}
                            {% endfor %}
                        </td>
                        <td class="demo-tdh">{{ p.cost }}</td>
                        <td class="demo-tdh">{{ p.timespan }}</td>
                        <td class="demo-tdh">{{ p.goal }}</td>
                        <td class="demo-tdh">{{ p.proposed_date }}</td>
                        <td class="demo-tdh">
                            <input type="hidden" id="core_id" value="{{ p.core_id }}">
                            <button class="btn btn-success btn-proposal-edit" data-core-id="{{ p.core_id }}" onclick="location.href=`{% url 'observer:update-proposal-form' p.core_id %}`;">Edit
                            </button>
                        </td>
                    </tr>
                {% endfor %}
            </table>

        </div>
    </main>

{% endblock %}