Code_Samurai_Hackathon/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import observer.views as observer_views
import observer.authentication_module as observer_au

urlpatterns = [
                  path('admin/', admin.site.urls),
                  # path('', observer_views.load, ''),
                  path('', include('observer.urls', namespace='observer')),
                  path('login/', observer_au.log_in, name='login'),
                  path('logout/', observer_au.logout_request, name='logout'),
                  path('registration/', observer_au.registration, name='register'),
                  path('utility/', include('utility_engines.urls', namespace='utility')),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

observer/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import observer.views as observer_views
import observer.review_proposal as review_view

app_name = 'observer'

urlpatterns = [
    path('api/projects/', observer_views.projects, name='projects'),
    path('api/all-projects/', observer_views.all_projects, name='all-projects'),
    path('api/projects/filter', observer_views.filter_projects, name='filter_projects'),
    path('', observer_views.load, name='home'),
    path('post_feedback/', observer_views.post_feedback, name='post_feedback'),
    path('project-proposal/', observer_views.project_proposal, name='project-proposal'),
    # path('project-proposal/update-proposal/', observer_views.update_proposal, name='update-proposal'),
    path('update-proposal/<int:pk>/', observer_views.proposal_update_form, name='update-proposal-form'),
    path('add-rating/', observer_views.add_rating, name='add-rating'),
    path('review-project-proposal/<int:pk>/', review_view.detail_project_proposal, name='detail-project-proposal'),
    path('approve-proposal/<int:pk>/', review_view.approve_proposal, name='approve-proposal'),
    path('reject-proposal/<int:pk>/', review_view.reject_proposal, name='reject-proposal'),
    path('review-project-proposal/', review_view.review_project_proposal, name='review-project-proposal'),
    path('running-project/', review_view.running_project, name='running-project'),
    path('running-project/<int:pk>/', review_view.detail_running_project, name='detail-running-project'),

    path('export-data/', observer_views.export_data, name='export-data'),
    path('export-data-search/', observer_views.export_data_search, name='export-data-search'),
    path('test/', observer_views.test_func, name='test'),
    path('404/', observer_views.load_not_found, name='404'),
    # path('export-data/export-csv/', observer_views.csv_extractor, name='csv-extractor'),
]

templates/components/cards.html
<div class="row">
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-primary text-white mb-4">
                                    <div class="card-body">Primary Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-warning text-white mb-4">
                                    <div class="card-body">Warning Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-success text-white mb-4">
                                    <div class="card-body">Success Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-3 col-md-6">
                                <div class="card bg-danger text-white mb-4">
                                    <div class="card-body">Danger Card</div>
                                    <div class="card-footer d-flex align-items-center justify-content-between">
                                        <a class="small text-white stretched-link" href="#">View Details</a>
                                        <div class="small text-white"><i class="fas fa-angle-right"></i></div>
                                    </div>
                                </div>
                            </div>
                        </div>

templates/components/charts.html
<div class="row">
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-area me-1"></i>
                                        Area Chart Example
                                    </div>
                                    <div class="card-body"><canvas id="myAreaChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                            <div class="col-xl-6">
                                <div class="card mb-4">
                                    <div class="card-header">
                                        <i class="fas fa-chart-bar me-1"></i>
                                        Bar Chart Example
                                    </div>
                                    <div class="card-body"><canvas id="myBarChart" width="100%" height="40"></canvas></div>
                                </div>
                            </div>
                        </div>

templates/components/location_register_map.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/leaflet_map.css' %}">
<link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css"/>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
        crossorigin=""></script>
<script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>


<div id="map">
</div>


<script src="{% static 'js/location_register_map.js' %}"></script>

{# leaflet js  #}

templates/components/map.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/leaflet_map.css' %}">
<link rel="stylesheet" href="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.css"/>
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin=""/>
<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
        crossorigin=""></script>
<script src="https://unpkg.com/leaflet-routing-machine@latest/dist/leaflet-routing-machine.js"></script>


<div id="map">
</div>

<div class="d-flex justify-content-end">
    <div class="dropdown ms-auto">
        <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
            Category
        </button>
        <ul class="dropdown-menu" id="category-dropdown">

            {% for project in projects %}
                <li>
                    <div class="form-check">
                        {#                                        <input class="form-check-input" onchange="filter_map_marker({{ project.category }})" type="checkbox" value="{{ project.category }}" id="flexCheckDefault">#}
                        <input class="form-check-input marker-filter" type="checkbox"
                               value="{{ project.category }}" id="{{ project.category }}">
                        <label class="form-check-label" for="{{ project.category }}">
                            {{ project.category }}
                        </label>
                    </div>
                </li>
            {% endfor %}


        </ul>
    </div>
</div>

<script src="{% static 'js/map.js' %}"></script>

{# leaflet js  #}

templates/components/modal.html
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Project Details</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    <strong>Project Name: </strong>
                    <text-input-area id="pop-up-project-name"></text-input-area>
                </p>

                <p>
                    <strong>Agency : </strong>
                    <text-input-area id="pop-up-agency"></text-input-area>
                </p>
                <p>
                    <strong>Expected Cost : </strong>
                    <text-input-area id="pop-up-expected-cost"></text-input-area>
                </p>
                <p>
                    <strong>Actual Cost : </strong>
                    <text-input-area id="pop-up-actual-cost"></text-input-area>
                </p>
                <p>
                    <strong>Expected Time Span: </strong>
                    <text-input-area id="pop-up-expected-time-span"></text-input-area>
                </p>
                <p>
                    <strong>Goal: </strong>
                    <text-input-area id="pop-up-goal"></text-input-area>
                </p>
                <p>
                    <strong>Project Start Time: </strong>
                    <text-input-area id="pop-up-start-time"></text-input-area>
                </p>
                <p>
                    <strong>Completion Percentage: </strong>
                    <text-input-area id="pop-up-completion-time"></text-input-area>
                </p>


                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="form-issue" class="form-label">
                            <strong>
                                Feedback:
                            </strong>
                        </label>
                        <textarea class="form-control" id="form-issue" rows="3"></textarea>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button class="btn btn-primary submit-issue">Add Feedback</button>
                    </div>
                </form>

                {% include 'components/rating.html' %}
                <!-- <p>
                    <strong>Location Coordinates: </strong>
                    <text-input-area id="pop-up-coord">  </text-input-area>
                </p> -->


            </div>
        </div>
    </div>
</div>
{# project name #}
{# list of lication #}
{#agency#}
{#expected_cost#}
{#actual_cost#}
{#expected_time_span#}
{#goal#}
{#start_date#}
{#completion_date#}

templates/components/rating.html
{% load static %}
<style>
    .rating {
        display: flex;
        flex-direction: row-reverse;
        justify-content: center
    }

    .rating > input {
        display: none
    }

    .rating > label {
        position: relative;
        width: 1em;
        font-size: 2vw;
        color: #1c1f23;
        cursor: pointer
    }

    .rating > label::before {
        content: "\2605";
        position: absolute;
        opacity: 0
    }

    .rating > label:hover:before,
    .rating > label:hover ~ label:before {
        opacity: 1 !important
    }

    .rating > input:checked ~ label:before {
        opacity: 1
    }

    .rating:hover > input:checked ~ label:before {
        opacity: 0.4
    }


</style>
<form>
    {% csrf_token %}
    <h4>Add a rating: </h4>
    <div class="rating">
        <input type="radio" name="rating" value="5" id="5">
        <label for="5">☆</label>
        <input type="radio" name="rating" value="4" id="4">
        <label for="4">☆</label>
        <input type="radio" name="rating" value="3" id="3">
        <label for="3">☆</label>
        <input type="radio" name="rating" value="2" id="2">
        <label for="2">☆</label>
        <input type="radio" name="rating" value="1" id="1">
        <label for="1">☆</label>
    </div>
    <button class="btn btn-primary submit-rating">Submit</button>
</form>

<script src="{% static 'js/add-rating.js' %}"></script>

templates/components/running_project.html
{% extends 'base/base.html' %}
{% load static %}

{% block projects %}
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Government Agency Running Projects</h1>
            <div class="row">
                <div class="col shadow-lg m-4">
                    <div class="row text-center mb-3">
                        <h2>Running Project</h2>

                        <table class="demo-table">
                            <tr class="demo-tr">
                                <th class="demo-tdh">Name</th>
                                <th class="demo-tdh">Location</th>
                                <th class="demo-tdh">Cost</th>
                                <th class="demo-tdh">Timespan</th>
                                <th class="demo-tdh">Goal</th>
                                <th class="demo-tdh">Start Date</th>
                                <th class="demo-tdh">End Estimation</th>
                            </tr>
                            {% for p in context %}
                                <tr class="demo-tr">
                                    <td class="demo-tdh">{{ p.name }}</td>
                                    <td class="demo-tdh">
                                        {% for l in p.location %}
                                            {{ l }}
                                        {% endfor %}
                                    </td>
                                    <td class="demo-tdh">{{ p.cost }}</td>
                                    <td class="demo-tdh">{{ p.timespan }}</td>
                                    <td class="demo-tdh">{{ p.goal }}</td>
                                    <td class="demo-tdh">{{ p.start_date }}</td>
                                    <td class="demo-tdh">{{ p.expected_end }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

templates/components/sidebar.html
{% load static %}

<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="{% url 'observer:home' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Dashboard
                </a>
                <a class="nav-link" href="{% url 'observer:project-proposal' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Project Proposal
                </a>

                <a class="nav-link" href="{% url 'observer:review-project-proposal' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Review Project
                </a>

                <a class="nav-link" href="{% url 'observer:running-project' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Running Project
                </a>
                <a class="nav-link" href="{% url 'observer:export-data' %}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    Export Data
                </a>
                <div class="sb-sidenav-menu-heading">Interface</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts"
                   aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    Layouts
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne"
                     data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="layout-static.html">Static Navigation</a>
                        <a class="nav-link" href="layout-sidenav-light.html">Light Sidenav</a>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages"
                   aria-expanded="false" aria-controls="collapsePages">
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Pages
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapsePages" aria-labelledby="headingTwo"
                     data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                           data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                            Authentication
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne"
                             data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="login.html">Login</a>
                                <a class="nav-link" href="register.html">Register</a>
                                <a class="nav-link" href="password.html">Forgot Password</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse"
                           data-bs-target="#pagesCollapseError" aria-expanded="false"
                           aria-controls="pagesCollapseError">
                            Error
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne"
                             data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="401.html">401 Page</a>
                                <a class="nav-link" href="404.html">404 Page</a>
                                <a class="nav-link" href="500.html">500 Page</a>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="charts.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Charts
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Tables
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as:</div>
            {{ user }}
        </div>
    </nav>
</div>

templates/components/single_proposal.html
{% extends 'base/base.html' %}
{% load static %}

{% block projects %}
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Proposed Projects by the Agency</h1>
            <div class="row">
                <div class="col shadow-lg m-4">
                    <div class="row text-center mb-3">
                        <h2>Propose Project</h2>
                    </div>
                    <div class="proposal-form form-control">
                        <form method="post" action="{% url 'observer:project-proposal' %}">
                            {% csrf_token %}
                            <label for="propose-form-name">Project name:</label><br>
                            <input type="text" id="propose-form-name" class="form-control" name="propose-form-name" value="{{ data.name }}" readonly><br>

                            <label for="propose-form-area">Location Area:</label><br>
                            <input class="form-control" type="text" id="propose-form-area form-control"
                                   name="propose-form-area" value="{{data.area}}" readonly><br>
                            <label for="propose-form-lat">Latitude</label><br>
                            <input class="form-control" type="text" id="propose-form-lat" name="propose-form-lat"
                                   required value="{{data.lat}}" readonly><br>
                            <label for="propose-form-long">Longitude</label><br>
                            <input class="form-control" type="text" id="propose-form-long" name="propose-form-long"
                                   required value="{{data.long}}" readonly><br>


                            <label for="propose-form-cost">Project cost:</label><br>
                            <input class="form-control" type="number" id="propose-form-cost"
                                   name="propose-form-cost" value="{{data.cost}}" readonly><br>

                            <label for="propose-form-timespan">Project timespan:</label><br>
                            <input class="form-control" type="number" id="propose-form-timespan"
                                   name="propose-form-timespan" value="{{data.timespan}}" readonly><br>

                            <label for="propose-form-goal">Project goal:</label><br>
                            <input class="form-control" type="textarea" id="propose-form-goal" name="propose-form-goal" value="{{data.goal}}" readonly><br>

                            <label for="propose-form-proposed-date">Proposed Date:</label><br>
                            <input class="form-control" type="textarea" id="propose-form-proposed-date" name="propose-form-proposed-date" value="{{data.proposed_date}}" readonly><br>

                            <label for="propose-form-start">Starting Date Estimation:</label><br>
                            <input class="form-control" type="textarea" id="propose-form-start" name="propose-form-start" value="{{data.estimate_start}}" readonly><br>

                            <label for="propose-form-end">Ending Date Estimation</label><br>
                            <input class="form-control" type="textarea" id="propose-form-end" name="propose-form-end" value="{{data.estimated_end}}" readonly><br>

                            <div class="row text-center px-2">
                                <div>
                                    <button class="btn btn-success" onclick="location.href=`{% url 'observer:approve-proposal' data.id %}`;">Approve
                                    </button>
                                    <button class="btn btn-danger" onclick="location.href=`{% url 'observer:reject-proposal' data.id %}`;">Reject
                                    </button>
                                </div>
                            </div>

                        </form>
                    </div>
                </div>
                <div class="col shadow-lg m-4">
                    {% include 'components/location_register_map.html' %}

                    <div class="d-flex justify-content-center">
                        <h4 class="mt-4">
                            Drag the marker to select the project coordinate
                        </h4>
                    </div>
                </div>
            </div>

        </div>
    </main>

{% endblock %}

templates/components/single_running.html
{% extends 'base/base.html' %}
{% load static %}

{% block projects %}
    <main>
        <div class="container-fluid px-4">
            <h1 class="mt-4">Proposed Projects by the Agency</h1>
            <div class="row">
                <div class="col shadow-lg m-4">
                    <div class="row text-center mb-3">
                        <h2>Propose Project</h2>
                    </div>
                    <div class="proposal-form form-control">
                        <form method="post" action="{% url 'observer:project-proposal' %}">
                            {% csrf_token %}
                            <label for="propose-form-name">Project name:</label><br>
                            <input type="text" id="propose-form-name" class="form-control" name="propose-form-name" value="{{ data.name }}" readonly><br>

                            <label for="propose-form-area">Location Area:</label><br>
                            <input class="form-control" type="text" id="propose-form-area form-control"
                                   name="propose-form-area" value="{{data.area}}" readonly><br>
                            <label for="propose-form-lat">Latitude</label><br>
                            <input class="form-control" type="text" id="propose-form-lat" name="propose-form-lat"
                                   required value="{{data.lat}}" readonly><br>
                            <label for="propose-form-long">Longitude</label><br>
                            <input class="form-control" type="text" id="propose-form-long" name="propose-form-long"
                                   required value="{{data.long}}" readonly><br>


                            <label for="propose-form-cost">Project cost:</label><br>
                            <input class="form-control" type="number" id="propose-form-cost"
                                   name="propose-form-cost" value="{{data.cost}}" readonly><br>

                            <label for="propose-form-timespan">Project timespan:</label><br>
                            <input class="form-control" type="number" id="propose-form-timespan"
                                   name="propose-form-timespan" value="{{data.timespan}}" readonly><br>

                            <label for="propose-form-goal">Project goal:</label><br>
                            <input class="form-control" type="textarea" id="propose-form-goal" name="propose-form-goal" value="{{data.goal}}" readonly><br>

                            <label for="propose-form-proposed-date">Proposed Date:</label><br>
                            <input class="form-control" type="textarea" id="propose-form-proposed-date" name="propose-form-proposed-date" value="{{data.proposed_date}}" readonly><br>

                            <label for="propose-form-start">Starting Date Estimation:</label><br>
                            <input class="form-control" type="textarea" id="propose-form-start" name="propose-form-start" value="{{data.estimate_start}}" readonly><br>

                            <label for="propose-form-end">Ending Date Estimation</label><br>
                            <input class="form-control" type="textarea" id="propose-form-end" name="propose-form-end" value="{{data.estimated_end}}" readonly><br>

                            <div class="row text-center px-2">

                            </div>

                        </form>
                    </div>
                </div>
                <div class="col shadow-lg m-4">
                    {% include 'components/location_register_map.html' %}

                    <div class="d-flex justify-content-center">
                        <h4 class="mt-4">
                            Drag the marker to select the project coordinate
                        </h4>
                    </div>
                </div>
            </div>

        </div>
    </main>

{% endblock %}

templates/components/toast-message-failure.html
<div class="toast-container position-fixed bottom-0 end-0 p-3">
    <div id="failure-toast" class="toast" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
            <strong class="me-auto text-danger" id="toast-header-failure">Failed</strong>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <div class="toast-body" id="toast-msg-body-failure">

        </div>
    </div>
</div>

templates/components/topbar.html
{% load static %}

<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{% url 'observer:home' %}">Buet Noobs</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
            class="fas fa-bars"></i></button>
    <!-- Navbar Search-->

    <div class="d-none d-md-inline-block ms-auto me-0 me-md-3 my-2 my-md-0">
        <a class="btn btn-danger" href="{% url 'logout' %}"> Logout</a>
    </div>
    
</nav>